### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by tjscollins** [oakes/Nightlight#31]
Code completion doesn't seem to work properly for me in the current version of Chrome or Firefox.  The div elements appear, but they are empty/without any text.  There are no error messages in the logged in bash console nightlight was launched from.

![screenshot from 2017-05-07 06-31-12](https://cloud.githubusercontent.com/assets/507777/25775714/d2306a88-32ee-11e7-87f3-a3722e4b90ad.png)

**Comment by oakes** [comment]
Can't seem to reproduce this. I downloaded your old-school-library project and it appears to work on my machine:

![old-school-library](https://cloud.githubusercontent.com/assets/216147/25813203/a2dd6bac-33e6-11e7-9f8b-a725928d4863.png)

It looks like you're using Linux so that is one difference, but I don't know of any Linux-specific problem that might cause that. If you have any other info on your setup please let me know.

**Comment by tjscollins** [comment]
Seems to be working now.  Something must have been out of date and got updated.  No idea what though.  Thanks for checking.

**Comment by oakes** [comment]
No problem!

**Comment by glfeng318** [comment]
i got the same problem too with OS X 10.12.1 and Safari 10.0.1, also chromium did't work
